apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-frontend
  namespace: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: angular
  template:
    metadata:
      labels:
        app: angular
    spec:
      containers:
      - name: angular
        image: ${ECR_REPO}/angular-frontend:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        envFrom:
        - configMapRef:
            name: frontend-config
---
apiVersion: v1
kind: Service
metadata:
  name: angular-frontend
  namespace: frontend
spec:
  selector:
    app: angular
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP