apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: frontend
data:
  API_URL: "http://backend-service.backend.svc.cluster.local:8080"
  ENVIRONMENT: "production"
  FEATURES_ENABLED: "true"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: backend
data:
  SERVER_PORT: "8080"
  LOG_LEVEL: "info"
  DB_HOST: "${db_host}"
  DB_PORT: "5432"
  DB_NAME: "csidb"
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: backend
type: Opaque
data:
  # Base64 encoded placeholders - replace with actual values
  DB_USERNAME: YWRtaW4=  # admin
  DB_PASSWORD: UkVQTEFDRV9XSVRIX1NFQ1VSRV9QQVNTV09SRA==  # REPLACE_WITH_SECURE_PASSWORD